# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TransferModalUnfoldings <- function(S, d1, d2, r1, r2, r3) {
    .Call(`_tensorIA_TransferModalUnfoldings`, S, d1, d2, r1, r2, r3)
}

EstInteg <- function(Y, Z, S, A, B, C, mu, optsList) {
    .Call(`_tensorIA_EstInteg`, Y, Z, S, A, B, C, mu, optsList)
}

EstFR <- function(Y, Z) {
    .Call(`_tensorIA_EstFR`, Y, Z)
}

